import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Footer } from "@/components/Footer";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { LangSwitcher } from "@/components/LangSwitcher";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as "ar" | "en" | "fr")) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale} className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        dir={locale === "ar" ? "rtl" : "ltr"}
      >
        <NextIntlClientProvider messages={messages}>
          <div className='flex flex-col'>
            <LangSwitcher />
            <div className='flex-1'>{children}</div>
            <div className='fixed top-1/3 left-0 w-full h-full pointer-events-none z-[-1]'>
              <div className='floating-shapes w-[200px] h-[200px] top-[20%] left-[10%]'></div>
              <div className='floating-shapes w-[150px] h-[150px] top-[60%] right-[15%]'></div>
            </div>
            <Footer />
          </div>
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
